<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserLoginSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $userId = 1;
        $deviceTypes = ['Desktop', 'Mobile', 'Tablet'];
        $userAgents = [
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
            'Mozilla/5.0 (Linux; Android 11)',
            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        ];

        $now = Carbon::now();
        $startDate = $now->copy()->subDays(60);

        $data = [];

        // Generate logs for each day in the last 60 days
        while ($startDate->lte($now)) {
            $loginCount = rand(15, 60); // jumlah login per hari (boleh diubah)

            for ($i = 0; $i < $loginCount; $i++) {
                $timestamp = $startDate->copy()->addMinutes(rand(10, 600));

                $data[] = [
                    'usr_lg_user_id'      => $userId,
                    'usr_lg_ip_address'   => fake()->ipv4(),
                    'usr_lg_user_agent'   => $userAgents[array_rand($userAgents)],
                    'usr_lg_device_type'  => $deviceTypes[array_rand($deviceTypes)],
                    'usr_lg_logged_in_at' => $timestamp,
                    'usr_lg_sys_note'     => 'Generated by Seeder',

                    'usr_lg_created_by'   => $userId,
                    'usr_lg_updated_by'   => $userId,
                    'usr_lg_deleted_by'   => null,

                    'usr_lg_created_at'   => $timestamp,
                    'usr_lg_updated_at'   => $timestamp,
                    'usr_lg_deleted_at'   => null,
                ];
            }

            $startDate->addDay();
        }

        DB::table('user_login')->insert($data);
    }
}
